name: faker
version: 1.2.0
description: A library for generating fake data. faker is heavily inspired by the Python package faker and, the Ruby package ffaker.
homepage: https://github.com/drager/faker
author: Jesper HÃ¥kansson <jesper@jesperh.se>
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.2.0
